#!/bin/bash

cd
git clone git://github.com/sstephenson/rbenv.git .rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

rbenv install 2.0.0-p353
rbenv global 2.0.0-p353
ruby -v

echo "gem: --no-ri --no-rdoc" > ~/.gemrc

cd ~/.rbenv/plugins
git clone git://github.com/jf/rbenv-gemset.git
