#!/bin/bash
cd
mkdir ~/bin
cd bin
git clone git@github.com:sigurdga/gnome-terminal-colors-solarized.git
cd gnome-terminal-colors-solarized
./set_dark.sh
mkdir ~/.fonts
cd ~/.fonts
wget --no-check-certificate https://github.com/Lokaltog/powerline-fonts/raw/master/Inconsolata/Inconsolata%20for%20Powerline.otf -O InconsolataForPowerline.otf
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cp ~/.zshrc ~/.zshrc.orig
wget --no-check-certificate https://raw.github.com/cmol/dotfiles/master/.zshrc -O ~/.zshrc
chsh -s /bin/zsh
echo "Logout and login again for chsh to take effect"
